name: Upload release assets

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build-deb:
    name: Create zip for publishing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          zip -r twingate-status@guillaume-gambs.github.io.zip icons/ schemas/org.gnome.shell.extensions.twingate-status.gschema.xml extension.js prefs.js locale.js metadata.json stylesheet.css LICENSE

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./twingate-status@guillaume-gambs.github.io.zip
          asset_name: twingate-status@guillaume-gambs.github.io.zip
          tag: ${{ github.ref }}